spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/yanger?useUnicode=true&amp;characterEncoding=utf-8
    username: root
    password: 1234
  redis:
    host: localhost
    port: 6379
    password: 1234
    timeout: 180000
  servlet:
    multipart:
      #设置上传文件根路径
      location: D:/

#日志文件位置
logging:
  file: D:/code/log/yanger.log

#添加服务器ip，供获取图片
yanger:
  file-load-prefix: 

# 本地开发的时候可以关掉了swagger对于token的验证
swagger:
  token-check: true